import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const DB_PROFILES = {
  postgres: {
    DATABASE_PROVIDER: 'postgres',
    DATABASE_ENV: 'local',
    DATABASE_MIGRATE_MODE: 'prisma',
    DATABASE_URL: 'postgresql://postgres:postgres@127.0.0.1:5432/superapp',
    DATABASE_URL_DIRECT:
      'postgresql://postgres:postgres@127.0.0.1:5432/superapp',
  },
  supabase: {
    DATABASE_PROVIDER: 'supabase',
    DATABASE_ENV: 'local',
    DATABASE_MIGRATE_MODE: 'prisma',
    DATABASE_URL:
      'postgresql://postgres:postgres@127.0.0.1:54322/postgres',
    DATABASE_URL_DIRECT:
      'postgresql://postgres:postgres@127.0.0.1:54322/postgres',
  },
  mongodb: {
    DATABASE_PROVIDER: 'mongodb',
    DATABASE_ENV: 'local',
    DATABASE_MIGRATE_MODE: 'manual',
    DATABASE_URL: 'mongodb://127.0.0.1:27017/superapp',
  },
};

export function writeEnvLocal(projectDir, { databaseId, appName }) {
  const examplePath = join(projectDir, '.env.example');
  let base = '';
  if (existsSync(examplePath)) {
    base = readFileSync(examplePath, 'utf8');
  }

  const db = DB_PROFILES[databaseId] ?? DB_PROFILES.postgres;
  const lines = base.split('\n').filter((line) => {
    const key = line.split('=')[0]?.trim();
    return !key?.startsWith('DATABASE_');
  });

  const dbLines = Object.entries(db).map(([k, v]) => `${k}=${v}`);
  const appLines = [
    `APP_NAME=${appName}`,
    'NEXT_PUBLIC_API_URL=http://localhost:8080',
    'API_PORT=8080',
    'WEB_PORT=4000',
  ];

  const out = [...lines, '', '# --- Generated by superapp init ---', ...dbLines, '', ...appLines, ''].join(
    '\n',
  );
  writeFileSync(join(projectDir, '.env.local'), out);
}
