import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT } from './profile.mjs';
import { formatProjectTree, slugify } from './paths.mjs';

const TOOL_FILES = {
  cursor: { file: 'CURSOR.md', specialist: 'Engineer' },
  claude: { file: 'CLAUDE.md', specialist: 'Orchestrator' },
  chatgpt: { file: 'CHATGPT.md', specialist: 'Orchestrator' },
  codex: { file: 'CODEX.md', specialist: 'Engineer' },
  gemini: { file: 'GEMINI.md', specialist: 'Researcher' },
};

export function writeIdeBundle(projectDir, profile) {
  const outDir = join(projectDir, '.superapp', 'ai');
  mkdirSync(outDir, { recursive: true });

  const starterDir = join(REPO_ROOT, 'prompts', 'starter');
  const triggersDir = join(REPO_ROOT, 'prompts', 'triggers');
  const manifest = [];

  for (const tool of profile.aiTools) {
    const meta = TOOL_FILES[tool.id];
    if (!meta) continue;
    const src = join(REPO_ROOT, meta.file);
    if (existsSync(src)) {
      copyFileSync(src, join(outDir, meta.file));
    }
    manifest.push({ tool: tool.id, file: meta.file, specialist: meta.specialist });
  }

  copyFileSync(
    join(REPO_ROOT, 'team', 'ADAPTER-PROMPT.md'),
    join(outDir, 'ADAPTER-PROMPT.md'),
  );

  const pathToken = profile.projectPath ?? 'projects/your-app';
  const hostToken = profile.host?.id ?? 'local-only';
  for (const name of [
    '00-first-session.md',
    '01-spin-up-project.md',
    '02-add-feature.md',
    '03-fix-bug.md',
    '04-deploy-staging.md',
    '05-wordpress-site.md',
  ]) {
    const src = join(starterDir, name);
    if (!existsSync(src)) continue;
    let text = readFileSync(src, 'utf8');
    text = text
      .replaceAll('{{PROJECT_PATH}}', pathToken)
      .replaceAll('{{HOST_ID}}', hostToken);
    writeFileSync(join(outDir, name), text);
  }

  mkdirSync(join(outDir, 'triggers'), { recursive: true });
  const triggersIndex = join(triggersDir, 'INDEX.md');
  if (existsSync(triggersIndex)) {
    copyFileSync(triggersIndex, join(outDir, 'triggers', 'INDEX.md'));
  }
  for (const name of [
    'create-new-app.md',
    'bootstrap-github.md',
    'check-stack.md',
    'run-stack.md',
    'git-pull.md',
    'git-push.md',
    'hosting-setup.md',
    'deploy-staging.md',
    'deploy-production.md',
    'leak-scan.md',
    'run-tests.md',
    'switch-database.md',
    'interactive-init.md',
  ]) {
    const src = join(triggersDir, name);
    if (!existsSync(src)) continue;
    let text = readFileSync(src, 'utf8');
    text = text
      .replaceAll('{{PROJECT_PATH}}', pathToken)
      .replaceAll('{{APP_SLUG}}', profile.projectSlug ?? slugify(profile.appName))
      .replaceAll('{{APP_NAME}}', profile.appName);
    writeFileSync(join(outDir, 'triggers', name), text);
  }

  const startMd = buildAiStartMarkdown(profile, manifest);
  writeFileSync(join(outDir, 'AI-START-HERE.md'), startMd);
  writeFileSync(join(projectDir, 'AI-START-HERE.md'), startMd);

  updateTeamState(projectDir, profile);

  return outDir;
}

function buildAiStartMarkdown(profile, manifest) {
  const tools = manifest.map((m) => `- **${m.tool}** → paste \`.superapp/ai/ADAPTER-PROMPT.md\` then read \`.superapp/ai/${m.file}\``).join('\n');

  return `# AI start — ${profile.appName}

Generated by SuperApp init on ${new Date().toISOString().split('T')[0]}.

## Your choices

| Setting | Value |
|---------|--------|
| App | ${profile.appName} |
| Database | ${profile.database.label} |
| Host (docs) | ${profile.host.label} |
| Project folder | \`${profile.projectPath}/\` |

## Step 1 — Open your IDE / AI

${tools}

## Step 2 — First message (copy all)

\`\`\`
Paste team/ADAPTER-PROMPT.md from this repo, then say:

"I initialized SuperApp for app '${profile.appName}' with ${profile.database.id} database.
Read team/STATE.md and team/HANDOFF.md. From project root \`${profile.projectPath}/\`, run: pnpm run db:validate"
\`\`\`

## AI triggers (say these phrases)

See \`.superapp/ai/triggers/INDEX.md\` — e.g. **create new app**, **bootstrap github**, **check the stack**, **run the stack**, **push to github**, **setup hosting**, **deploy staging** (requires \`--confirm\`).

## Starter prompts (in \`.superapp/ai/\`)

| File | Use when |
|------|----------|
| 00-first-session.md | Brand-new to the stack |
| 01-spin-up-project.md | New feature from blueprint |
| 02-add-feature.md | Implement one blueprint section |
| 03-fix-bug.md | Debug failing test or API |
| 04-deploy-staging.md | Staging deploy (human gate) |
| 05-wordpress-site.md | WordPress / shared host track |

## Security

- Never paste production secrets into chat
- \`.env.local\` is gitignored — keep it that way
- Run \`./scripts/leak-scan.sh\` before public push

## Project layout

\`\`\`
${formatProjectTree(profile.workspaceRoot ?? join(REPO_ROOT, 'projects'), profile.projectSlug ?? slugify(profile.appName))}
\`\`\`

## Playbooks

- Host: \`playbooks/hosting/${profile.host.id}/README.md\` (curriculum repo)
- Database: \`playbooks/databases/${profile.database.playbook}.md\`
`;
}

function updateTeamState(projectDir, profile) {
  const statePath = join(projectDir, 'team', 'STATE.md');
  if (!existsSync(statePath)) return;

  const content = readFileSync(statePath, 'utf8');
  const updated = content
    .replace('{{PROJECT}}', profile.appName)
    .replace('Not started', 'Initialized — local dev')
    .replace(
      '- None',
      `- App: ${profile.appName}\n- DB: ${profile.database.id}\n- Host playbook: ${profile.host.id}`,
    );
  writeFileSync(statePath, updated);
}
